# Generated by Django 6.0.4 on 2026-04-20 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_news_shop_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='shop_sizes',
        ),
    ]
